---
name: Publish Docker images to Docker Hub
on:
  push:
      branches: [ master ] # Set which branch to trigger this flow, e.q. [ master, develop ]
jobs:
  push_images_to_dockerhub:
    name: Push images to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push image
        id: build_publish_image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
      - name: Image digest
        run: echo ${{ steps.build_publish_image.outputs.digest }}
